### ISSUE TITLE
Connection attempt failed

### ISSUE THREAD

**Issue by Bentechy66** [aluttik/pizzapi#21]
getting this error when using the example code. What's going on?

```Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05C67970>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\packages\urllib3\util\retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='order.dominos.com', port=443): Max retries exceeded with url: /power/store-locator?s=700%20Pennsylvania%20Avenue%20NW&c=Washington,%20DC,%2020408&type=Delivery (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05C67970>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    store = address.closest_store()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pizzapi\address.py", line 34, in closest_store
    stores = self.nearby_stores(service=service)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pizzapi\address.py", line 29, in nearby_stores
    data = request_json(self.urls.find_url(), line1=self.line1, line2=self.line2, type=service)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pizzapi\utils.py", line 6, in request_json
    r = requests.get(url.format(**kwargs))
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.13.0-py3.6.egg\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='order.dominos.com', port=443): Max retries exceeded with url: /power/store-locator?s=700%20Pennsylvania%20Avenue%20NW&c=Washington,%20DC,%2020408&type=Delivery (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05C67970>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))```

**Comment by Bentechy66** [comment]
On inspection it seems that `order.dominos.com` does not actually exist

**Comment by aluttik** [comment]
@Bentechy66: No, `orders.dominos.com` does still exist... Check out the url with your browser: https://order.dominos.com/power/store-locator?s=700%20Pennsylvania%20Avenue%20NW&c=Washington,%20DC,%2020408&type=Delivery

To me it seems like this has something to do with a shoddy connection or maybe with your installation of requests. Or hey, maybe you exceeded their rate limit? It's hard to say.

In any case, I'm not really maintaining this repo anymore. I'm mostly just leaving it up now in case more people want to fork it. If you want to submit a PR I'll take a look at it, but don't expect a fix for this to roll out any time soon.

**Comment by Bentechy66** [comment]
Hmm, strange, I can access the site on my phone but not my PC. I will look into this on my end.
